### ISSUE TITLE
required fields in frontend and backend

### ISSUE THREAD

**Issue by koykoy027** [koykoy027/iprotect#50]
### Personal Details
- [ ] `Clarify Date of intake` if auto or pretext
- [ ] Remove required fields in `Ethnicity`

---

### Incident details
- [ ] clarify `date of intake` if auto or pretext

---

### Perpetrator details
- [x] `birthday` remove required fields
- [x] `age` remove required fields
- [x] clarify `sex` if required or not
- [x] `nationality` remove required fields
- [x] `religion` remove required fields
- [x] clarify `is perpetrator minor` if required fields
- [x] remove required fields `perp_d_last_name`, `perp_d_first_name`, 'perp_d_middle_name'
- [x] remove required fields `perp_d_birthdate `, `perp_d_age`, `perp_d_nationality`, `perp_d_religion`
- [x] remove required fields `perp_d rel_guar_perp`

---

### Intervention details
- [ ] `If Status is Provided, Provide Date` disabled the input fields `if status is provided`

![image](https://github.com/Real-Faith-Solutions/gender-based-violence-management-system/assets/96485178/b27abb26-bffb-485a-a744-a4026f8a859f)

**Comment by koykoy027** [comment]
@Jhunriz pa next neto

**Comment by Jhunriz** [comment]
paano ma done to boss personal details nalang saka incidence dito

**Comment by Jhunriz** [comment]
- Done
